x-service-templates:
  api: &api
    build: .
    depends_on:
      - db
    environment:
      PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      POSTGRES_HOST: postgres-db
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "90MB"

services:
  db:
    image: postgres:17.5-alpine
    container_name: postgres-db
    hostname: postgres-db
    environment:
      POSTGRES_DB: rinha_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "250MB"

  api-01:
    <<: *api
    container_name: api-01
    hostname: api-01

  api-02:
    <<: *api
    container_name: api-02
    hostname: api-02

  lb:
    image: nginx:1.29.0-alpine
    container_name: load-balancer
    ports:
      - "9999:9999"
    depends_on:
      - api-01
      - api-02
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "10MB"

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    name: payment-processor
    external: true
